#!/usr/bin/env python3
"""One-off helper to write Data/theory-questions.json from embedded question list."""
import json
from pathlib import Path

# Paste of theory questions (ids 1–50)
QUESTIONS = json.loads(r"""
[
  {"id": 1, "category": "Basic Obligations", "question": "According to Chapter 1, Section 5 of the Traffic Ordinance, who is primarily responsible for ensuring a vehicle is not used in violation of the law?", "options": ["Only the driver", "Only the registered owner", "The owner, but only for Chapter 4 provisions if someone else drives", "Both driver and owner are always equally responsible"], "answer": "The owner, but only for Chapter 4 provisions if someone else drives", "explanation": "Chapter 1, Section 5 states: The owner is responsible for ensuring the vehicle is not used in violation of the ordinance. However, if someone else is driving, the owner's responsibility is limited to the provisions in Chapter 4 (vehicle equipment and inspection)."},
  {"id": 2, "category": "Traffic Rules", "question": "What is the default speed limit within a built-up area (tättbebyggt område) when no speed sign is posted?", "options": ["30 km/h", "40 km/h", "50 km/h", "60 km/h"], "answer": "50 km/h", "explanation": "Chapter 3, Section 17, first paragraph: Within a built-up area, vehicles may not be driven at a speed exceeding 50 kilometres per hour unless signs indicate otherwise."},
  {"id": 3, "category": "Traffic Rules", "question": "What is the general speed limit outside a built-up area on roads without signs?", "options": ["70 km/h", "80 km/h", "90 km/h", "100 km/h"], "answer": "70 km/h", "explanation": "Chapter 3, Section 17, third paragraph: Outside a built-up area, the baseline speed limit is 70 km/h. Higher limits may be posted, but without signs, 70 applies."},
  {"id": 4, "category": "Traffic Rules", "question": "On a road with a speed limit of 70 km/h or lower and at least two marked lanes in your direction, which lane may you use?", "options": ["Only the rightmost lane", "Only the leftmost lane", "Any lane that is most suitable for your onward journey", "You must stay in the middle lane if there are three"], "answer": "Any lane that is most suitable for your onward journey", "explanation": "Chapter 3, Section 7, fifth paragraph: On roads where the speed limit is 70 km/h or lower and there are at least two lanes in the same direction marked with road markings, drivers may choose the lane most suitable for their onward travel."},
  {"id": 5, "category": "Traffic Rules", "question": "At an uncontrolled intersection where no priority signs or signals exist, who has the right of way?", "options": ["The vehicle coming from the left", "The vehicle coming from the right", "The larger vehicle", "The vehicle that arrived first"], "answer": "The vehicle coming from the right", "explanation": "Chapter 3, Section 18: When two vehicle courses intersect, the driver has a duty to yield to vehicles approaching from the right, except where Sections 21–23 (e.g., exit from a property, roundabout rules) apply."},
  {"id": 6, "category": "Traffic Rules", "question": "If a police officer gives a traffic instruction that contradicts a traffic light, which must you follow?", "options": ["The traffic light", "The police officer's instruction", "Whichever is easier to follow", "The normal right-hand rule"], "answer": "The police officer's instruction", "explanation": "Chapter 2, Section 3: Road users must obey police instructions for traffic. Such instructions take precedence over all other signals and signs."},
  {"id": 7, "category": "Traffic Rules", "question": "A driver who has a duty to yield (väjningsplikt) must:", "options": ["Always come to a complete stop", "Only stop if a STOP sign is present", "Clearly show intent to yield by slowing or stopping early", "Proceed if the other vehicle is far away"], "answer": "Clearly show intent to yield by slowing or stopping early", "explanation": "Chapter 3, Section 5: A driver with a duty to yield must demonstrate this clearly by reducing speed in good time or stopping. They may proceed only if doing so does not cause danger or obstruction."},
  {"id": 8, "category": "Traffic Rules", "question": "What must a driver with a stop obligation (stopplikt) do at an intersection?", "options": ["Slow down and look carefully", "Stop at the stop line, or if none, immediately before the intersecting road", "Only stop if another vehicle is approaching", "Sound horn and proceed cautiously"], "answer": "Stop at the stop line, or if none, immediately before the intersecting road", "explanation": "Chapter 3, Section 19: A driver who has a stop obligation or must stop due to a traffic signal must stop at the stop line. If a stop line is missing, stop immediately before the traffic signal or before entering the intersecting road."},
  {"id": 9, "category": "Traffic Rules", "question": "Who has the right of way when entering a roundabout (cirkulationsplats)?", "options": ["The vehicle entering the roundabout", "All vehicles already inside the roundabout", "The fastest vehicle", "The vehicle that arrives first"], "answer": "All vehicles already inside the roundabout", "explanation": "Chapter 3, Section 22: A driver entering a roundabout has a duty to yield to every vehicle already circulating in the roundabout."},
  {"id": 10, "category": "Traffic Rules", "question": "On which side of the road must a vehicle be parked according to the main rule?", "options": ["On the left side in the direction of travel", "On the right side in the direction of travel", "On either side, as long as it is off the roadway", "On the side with the most available space"], "answer": "On the right side in the direction of travel", "explanation": "Derived from Chapter 3, Section 52 and established case law (RH 2013:55): Vehicles may only be stopped or parked on the right side in the direction of travel on public roads."},
  {"id": 11, "category": "Traffic Rules", "question": "How long, as a main rule, may a vehicle be parked on a street or public road on weekdays without special signs?", "options": ["12 hours", "24 hours", "48 hours", "72 hours"], "answer": "24 hours", "explanation": "The Traffic Ordinance states that a vehicle may not be parked for more than 24 consecutive hours on a street or public road on weekdays (excluding the day before a public holiday)."},
  {"id": 12, "category": "Traffic Rules", "question": "If you are involved in a traffic accident, what must you do?", "options": ["Leave immediately to call for help", "Stop, stay at the scene, help injured, and provide your information", "Only stop if someone is injured", "Exchange information only if damage exceeds a certain amount"], "answer": "Stop, stay at the scene, help injured, and provide your information", "explanation": "Chapter 2, Section 8: A road user involved in an accident must stop and remain. They must help the injured and participate in necessary measures, and provide name and address upon request."},
  {"id": 13, "category": "Traffic Rules", "question": "When you see children on or near the road, what speed must you maintain?", "options": ["The posted speed limit", "A sufficiently low speed adapted to the situation", "At least 30 km/h to avoid surprise", "No change, but sound the horn"], "answer": "A sufficiently low speed adapted to the situation", "explanation": "Chapter 3, Section 15: In addition to other specified cases, a driver must maintain a speed low enough given the circumstances when approaching children staying on or beside the road."},
  {"id": 14, "category": "Traffic Rules", "question": "Is it permitted to stop or park in a way that blocks access to another parked vehicle?", "options": ["Yes, if you leave a note", "Yes, for a short time only", "No, it is prohibited", "Only if the other vehicle is also illegally parked"], "answer": "No, it is prohibited", "explanation": "Chapter 3, Section 49, first point: A vehicle may not be parked in a way that prevents access to other vehicles or prevents them from being moved from their spot."},
  {"id": 15, "category": "Traffic Rules", "question": "If your vehicle breaks down and is forced to stop in a no-parking zone, what should you do?", "options": ["Leave it and call for help", "Move it to a suitable location as soon as possible", "Place a warning triangle and leave", "Wait for the police"], "answer": "Move it to a suitable location as soon as possible", "explanation": "Chapter 3, Section 51: If a vehicle becomes stationary due to an accident or breakdown in a place where stopping or parking is prohibited, the driver must ensure it is moved to a suitable location as soon as possible."},
  {"id": 16, "category": "Traffic Rules", "question": "What is the fundamental rule for following distance?", "options": ["At least 3 seconds", "At least 50 metres", "Adapted so there is no risk of collision if the vehicle ahead stops suddenly", "Equal to your vehicle's length per 10 km/h"], "answer": "Adapted so there is no risk of collision if the vehicle ahead stops suddenly", "explanation": "Chapter 3, Section 2: The distance to a vehicle ahead must be adapted so that there is no risk of collision if it slows down or stops. The distance must also allow for safe overtaking by others."},
  {"id": 17, "category": "Traffic Rules", "question": "Which lane should you normally use when driving on a multi-lane road?", "options": ["The leftmost lane", "The rightmost lane that is intended for your vehicle", "The middle lane", "Any lane, as long as you keep up with traffic"], "answer": "The rightmost lane that is intended for your vehicle", "explanation": "Chapter 3, Section 7, first paragraph: When driving on a road, vehicles must be driven in the lane that is farthest to the right in the direction of travel and that is intended for the vehicle."},
  {"id": 18, "category": "Traffic Rules", "question": "You are exiting a private driveway onto a main road. What is your obligation?", "options": ["You have right of way because you are exiting a property", "You must yield to all vehicles on the main road", "You must stop and then go regardless of traffic", "You have priority if you signal early"], "answer": "You must yield to all vehicles on the main road", "explanation": "Chapter 3, Section 21, third paragraph: A driver has a duty to yield to any vehicle whose path they cross when entering a road from a parking lot, property, gas station, or similar area."},
  {"id": 19, "category": "Traffic Rules", "question": "On which side must you normally overtake another vehicle?", "options": ["On the right", "On the left", "Either side if it is safe", "Only on the inside"], "answer": "On the left", "explanation": "Chapter 3, Section 31, first paragraph: Overtaking must be done on the left, except in the specific cases listed in the ordinance."},
  {"id": 20, "category": "Traffic Rules", "question": "When is overtaking on the right permitted?", "options": ["When the road is straight and visibility is good", "If the vehicle ahead is turning left or clearly preparing to turn left", "If the vehicle ahead is driving very slowly", "Never"], "answer": "If the vehicle ahead is turning left or clearly preparing to turn left", "explanation": "Chapter 3, Section 31, second paragraph: Overtaking on the right is permitted when the driver of the vehicle ahead is turning left or is clearly preparing for such a turn."},
  {"id": 21, "category": "Traffic Rules", "question": "May a cyclist overtake other vehicles on the right?", "options": ["Yes, always", "Yes, but only on the right", "Yes, if there is enough space", "No, cyclists must also overtake on the left"], "answer": "Yes, always", "explanation": "Chapter 3, Section 31, third paragraph: Cyclists and moped drivers may overtake vehicles other than bicycles and mopeds on the right side."},
  {"id": 22, "category": "Traffic Rules", "question": "What must a driver do when approaching a pedestrian crossing (zebra crossing) without traffic lights?", "options": ["Always stop before the crossing", "Adjust speed so that they can stop if a pedestrian is on or about to step onto the crossing", "Sound horn to alert pedestrians", "Proceed at the same speed but keep a lookout"], "answer": "Adjust speed so that they can stop if a pedestrian is on or about to step onto the crossing", "explanation": "Chapter 3, Section 15: A driver must maintain a sufficiently low speed at pedestrian crossings or other places where pedestrians cross, so they can stop if needed."},
  {"id": 23, "category": "Traffic Rules", "question": "Before turning right at an intersection with multiple lanes, from which lane should you turn?", "options": ["The lane farthest to the right", "The lane farthest to the left", "Any lane, as long as you signal", "The middle lane"], "answer": "The lane farthest to the right", "explanation": "Chapter 3, Section 25, first paragraph: Before an intersection with multiple lanes in the same direction, the driver must position the vehicle in the lane farthest to the right for a right turn, and the lane farthest to the left for a left turn."},
  {"id": 24, "category": "Traffic Rules", "question": "Is it allowed to reverse or turn around on a motorway?", "options": ["Yes, if no other vehicles are nearby", "Yes, only in emergencies", "No, it is strictly prohibited", "Yes, if you use hazard lights"], "answer": "No, it is strictly prohibited", "explanation": "Chapter 3, Section 46 and Chapter 9, Sections 1–2: Reversing and turning around are prohibited on motorways and motor traffic lanes under all circumstances."},
  {"id": 25, "category": "Traffic Rules", "question": "What is the penalty for failing to obey a police officer's traffic instruction?", "options": ["A warning only", "A fine", "Imprisonment up to 6 months", "Suspension of driving licence"], "answer": "A fine", "explanation": "While the Traffic Ordinance itself does not specify penalties, such an offense is typically subject to a fine under the Road Traffic Offenses Act (Vägtransportöverträdelselagen)."},
  {"id": 26, "category": "Traffic Rules", "question": "The basic rule for speed adaptation says you must consider all of the following EXCEPT:", "options": ["Weather and visibility", "Your own driving comfort", "Road and traffic conditions", "The vehicle's load and condition"], "answer": "Your own driving comfort", "explanation": "Chapter 3, Section 14: Speed must be adapted to road, terrain, weather, visibility, vehicle condition and load, and general traffic conditions – not to personal comfort."},
  {"id": 27, "category": "Traffic Rules", "question": "When must you use a parking disc (p-skiva)?", "options": ["Every time you park", "Only where a road sign requires it", "Only on private property", "Only between 8am and 6pm"], "answer": "Only where a road sign requires it", "explanation": "The requirement to use a parking disc is indicated by a specific road sign. The ordinance specifies placement and setting of the disc."},
  {"id": 28, "category": "Traffic Rules", "question": "Who has priority at a pedestrian crossing without traffic lights?", "options": ["Always the vehicle", "Pedestrians once they step onto the crossing", "Vehicles have priority if a pedestrian is waiting", "Pedestrians always have priority"], "answer": "Pedestrians always have priority", "explanation": "According to the Traffic Ordinance, a driver must yield to pedestrians at a pedestrian crossing. If a pedestrian is on the crossing or is about to step onto it, the driver must stop and let them cross."},
  {"id": 29, "category": "Traffic Rules", "question": "What is the legal blood alcohol concentration (BAC) limit for driving in Sweden?", "options": ["0.0‰", "0.2‰", "0.5‰", "0.8‰"], "answer": "0.2‰", "explanation": "The Swedish BAC limit is 0.2 per mille (0.02%). This is one of the strictest in the world – any detectable alcohol can lead to prosecution for drunk driving."},
  {"id": 30, "category": "Traffic Rules", "question": "When are winter tyres mandatory in Sweden?", "options": ["December 1 to March 31", "Whenever winter road conditions exist (snow, ice, slush) from December 1 to March 31", "November 1 to April 15", "Only when temperatures drop below 0°C"], "answer": "Whenever winter road conditions exist (snow, ice, slush) from December 1 to March 31", "explanation": "Winter tyres are required from December 1 to March 31 if winter conditions prevail. Outside these dates, they are not mandatory but can be used if conditions require."},
  {"id": 31, "category": "Traffic Rules", "question": "What is the maximum permitted speed for a passenger car towing a light trailer (without brakes) on a motorway?", "options": ["80 km/h", "90 km/h", "100 km/h", "110 km/h"], "answer": "80 km/h", "explanation": "According to the ordinance, a vehicle towing a light trailer (total weight not exceeding the towing vehicle's unladen weight) may not exceed 80 km/h on motorways, and lower on other roads."},
  {"id": 32, "category": "Traffic Rules", "question": "You are driving at night on an unlit road. When must you dip your headlights?", "options": ["Only when meeting another vehicle", "When meeting another vehicle or when following another vehicle closely", "Only when a vehicle behind you is flashing", "Never, use full beam always"], "answer": "When meeting another vehicle or when following another vehicle closely", "explanation": "Chapter 3, Section 65: When meeting another vehicle, you must dip your headlights to avoid dazzling. Similarly, when following another vehicle closely, you must dip your headlights."},
  {"id": 33, "category": "Traffic Rules", "question": "May you use hazard warning lights while driving?", "options": ["Yes, whenever you want to warn others", "Only when the vehicle is stationary and poses a hazard", "Yes, in heavy rain", "Only when reversing"], "answer": "Only when the vehicle is stationary and poses a hazard", "explanation": "Hazard warning lights are intended to indicate that a vehicle is stationary and causing a danger. Using them while moving is generally prohibited unless in exceptional circumstances (e.g., warning of a sudden queue ahead)."},
  {"id": 34, "category": "Vehicle Equipment", "question": "Which of the following is mandatory safety equipment in a passenger car in Sweden?", "options": ["Fire extinguisher and first-aid kit", "Warning triangle and high-visibility vest", "Spare tyre and jack", "Emergency hammer"], "answer": "Warning triangle and high-visibility vest", "explanation": "Chapter 4, Section 7: All motor vehicles must carry a warning triangle. High-visibility vests are also mandatory for all vehicles registered in Sweden. Fire extinguisher and first-aid kit are recommended but not required for passenger cars."},
  {"id": 35, "category": "Traffic Rules", "question": "What does a flashing red light at a railway crossing mean?", "options": ["Proceed with caution", "Stop and do not proceed until the light stops flashing", "Sound horn and proceed slowly", "The crossing is closed for maintenance only"], "answer": "Stop and do not proceed until the light stops flashing", "explanation": "A flashing red light at a railway crossing means a train is approaching or passing. You must stop completely and wait until the light stops flashing and the boom gates (if any) are fully raised."},
  {"id": 36, "category": "Traffic Rules", "question": "When may you use the hard shoulder (vägren) for driving?", "options": ["Whenever the main lane is congested", "Only to allow emergency vehicles to pass", "Never, unless permitted by a sign or in an emergency", "Only when overtaking slower vehicles"], "answer": "Never, unless permitted by a sign or in an emergency", "explanation": "The hard shoulder is intended for emergency stops only. Driving on the hard shoulder is prohibited except when a sign permits it (e.g., on some roads as an extra lane)."},
  {"id": 37, "category": "Traffic Rules", "question": "What is the minimum tread depth for summer tyres on a passenger car?", "options": ["1.0 mm", "1.6 mm", "2.0 mm", "3.0 mm"], "answer": "1.6 mm", "explanation": "According to the Vehicle Equipment Regulation (based on Chapter 4), the minimum tread depth is 1.6 mm for summer tyres. For winter tyres, the recommended minimum is 3 mm, but the legal minimum is also 1.6 mm."},
  {"id": 38, "category": "Traffic Rules", "question": "You approach a bus that has stopped at a bus stop with its hazard lights on and a 'stop' sign extended. What must you do?", "options": ["Slow down but continue", "Stop and not pass until the sign is retracted or hazard lights off", "Sound horn to alert the bus driver", "Overtake carefully at low speed"], "answer": "Stop and not pass until the sign is retracted or hazard lights off", "explanation": "When a school bus or public transport bus displays a 'stop' sign (or flashing lights), you must stop and not pass until the sign is retracted or the lights stop flashing. This is for passenger safety."},
  {"id": 39, "category": "Traffic Rules", "question": "What is the rule for using a mobile phone while driving?", "options": ["Prohibited only if you are holding it", "Allowed if you use a hands-free system", "Completely prohibited while the engine is running", "Allowed if you are stopped at a red light"], "answer": "Allowed if you use a hands-free system", "explanation": "Swedish law prohibits handling a mobile phone while driving (e.g., holding it to your ear, texting, etc.). Using a hands-free device (including voice control) is permitted, but you must still exercise proper care."},
  {"id": 40, "category": "Traffic Rules", "question": "A green arrow in a traffic light (beside the main red/yellow/green) means:", "options": ["You may turn in the direction of the arrow even if the main light is red", "You must wait for the main green light to appear", "The arrow is for pedestrians only", "You may go straight ahead"], "answer": "You may turn in the direction of the arrow even if the main light is red", "explanation": "A green arrow shown together with a red light indicates that you may proceed in the direction of the arrow after yielding to pedestrians and other vehicles. It is a 'filter arrow'."},
  {"id": 41, "category": "Traffic Rules", "question": "What does a yellow flashing traffic light mean?", "options": ["Stop immediately", "Prepare to stop, the red light will appear", "Proceed with caution and yield as if at an intersection with right-hand rule", "Speed up to clear the intersection"], "answer": "Proceed with caution and yield as if at an intersection with right-hand rule", "explanation": "A flashing yellow light means the traffic light is out of order or switched off. You must treat the intersection as if it had no signals – follow road signs or, if none, the right-hand rule."},
  {"id": 42, "category": "Traffic Rules", "question": "When may you sound your horn (warning signal) outside a built-up area?", "options": ["Only to avoid an accident", "To alert other drivers that you wish to overtake", "To greet a friend", "Only between 7am and 10pm"], "answer": "To alert other drivers that you wish to overtake", "explanation": "Outside built-up areas, you may sound the horn to warn another driver that you intend to overtake. Inside built-up areas, the horn may only be used to avert danger."},
  {"id": 43, "category": "Traffic Rules", "question": "What is the maximum speed for a passenger car towing a heavy trailer (with brakes) on a motorway?", "options": ["80 km/h", "90 km/h", "100 km/h", "110 km/h"], "answer": "80 km/h", "explanation": "Regardless of trailer brakes, the maximum permitted speed for a passenger car towing any trailer is 80 km/h on motorways and 80 km/h on other roads (unless a lower limit is posted)."},
  {"id": 44, "category": "Traffic Rules", "question": "You are driving in heavy fog. What light setting should you use?", "options": ["Parking lights only", "Dipped headlights", "Dipped headlights plus rear fog light if visibility is very poor", "Full beam headlights to see better"], "answer": "Dipped headlights plus rear fog light if visibility is very poor", "explanation": "Use dipped headlights (always required). Rear fog lights may be used only when visibility is severely reduced (under 200 metres). Full beam in fog reflects back and worsens visibility."},
  {"id": 45, "category": "Traffic Rules", "question": "What is the rule regarding overtaking at a pedestrian crossing?", "options": ["Overtaking is allowed if no pedestrians are present", "Overtaking is prohibited immediately before and on a pedestrian crossing", "Overtaking is allowed only if you are in a left-turn lane", "There is no special rule"], "answer": "Overtaking is prohibited immediately before and on a pedestrian crossing", "explanation": "Chapter 3, Section 40: Overtaking is prohibited immediately before and on a pedestrian crossing. This is to ensure that pedestrians are visible to all approaching drivers."},
  {"id": 46, "category": "Traffic Rules", "question": "You see a sign that says 'Mötande fordon har väjningsplikt' (oncoming vehicles must yield). What does this mean for you?", "options": ["You have priority over oncoming vehicles", "You must yield to oncoming vehicles", "The road ahead is narrow; you must wait for a passing bay", "It is a warning for a sharp bend"], "answer": "You have priority over oncoming vehicles", "explanation": "The sign indicates that oncoming traffic has a duty to yield to you. It is typically used on narrow roads where passing bays are provided for the yielding direction."},
  {"id": 47, "category": "Traffic Rules", "question": "What is the rule for entering a road from a bicycle path?", "options": ["You have right of way over all vehicles on the road", "You must yield to all vehicles on the road", "You must dismount and walk across", "Only yield to buses and trams"], "answer": "You must yield to all vehicles on the road", "explanation": "When entering a road from a bicycle path, you are leaving a separate track and must yield to all vehicles on the carriageway. The right-hand rule does not apply."},
  {"id": 48, "category": "Traffic Rules", "question": "How close to a pedestrian crossing may you park?", "options": ["5 metres before the crossing, 5 metres after", "10 metres before, 5 metres after", "Immediately before is allowed, but not on the crossing", "20 metres before"], "answer": "10 metres before, 5 metres after", "explanation": "Chapter 3, Section 49 (specific parking prohibitions): Parking is prohibited within 10 metres before a pedestrian crossing and within 5 metres after a pedestrian crossing, measured from the zebra markings."},
  {"id": 49, "category": "Traffic Rules", "question": "You are driving in a tunnel and the traffic comes to a standstill. What should you do?", "options": ["Turn off the engine and wait", "Keep a safe distance to the vehicle ahead and turn on your hazard lights to warn vehicles behind", "Immediately reverse to the nearest exit", "Sound your horn to alert others"], "answer": "Keep a safe distance to the vehicle ahead and turn on your hazard lights to warn vehicles behind", "explanation": "In a tunnel stoppage, maintain distance, turn on hazard warning lights to alert following traffic, and listen to tunnel radio/instructions. Do not reverse unless directed by emergency services."},
  {"id": 50, "category": "Traffic Rules", "question": "What is the rule regarding driving on the road shoulder (bankett) on ordinary roads?", "options": ["Allowed if the main road is damaged", "Prohibited, except when pulling over to stop or park", "Allowed for overtaking slowly moving vehicles", "Only for agricultural vehicles"], "answer": "Prohibited, except when pulling over to stop or park", "explanation": "Chapter 3, Section 9: Driving on the shoulder is prohibited. The shoulder is intended for stopping or parking. Driving on it is not permitted even to let others pass, except when entering or exiting a property."}
]
""")

out = Path(__file__).resolve().parents[1] / "Data" / "theory-questions.json"
out.write_text(json.dumps(QUESTIONS, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"Wrote {len(QUESTIONS)} questions to {out}")
